### ISSUE TITLE
Duplicate Slug

### ISSUE THREAD

**Issue by ipanardian** [rinvex/laravel-subscriptions#124]
Failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'one-month-free-trial-1826' for key 'plan_subscriptions_slug_unique'. 

How to prevent this? because the slug is generated automatically

**Comment by Omranic** [comment]
Thank you for your question and your patience.

This package uses [spatie/sluggable](https://github.com/spatie/laravel-sluggable#usage), so you can check the usage guide in order to tweak the slugs logic. By default we don't allow duplicate slugs, but if you want to change that behavior you may need to publish and adjust your migrations, and the models as well.

Let me know if you need any further help.
