### ISSUE TITLE
Wrong morph columns name of migrated table

### ISSUE THREAD

**Issue by yefta-me** [rinvex/laravel-subscriptions#155]
When I run `php artisan migrate`, I don't know why, but the result of this line: `$table->morphs('subscriber');` is creating `user_type` and `user_id` instead of `subscriber_id` and `subscriber_type`. on `plan_subscriptions` table. I didn't edit anything.

**Comment by abanghendri** [comment]
quite simillar to me, 
in my case, the migration always produce `subscriber_id` column with bigint even though I change `$table->morphs('subscriber');` to `$table->uuidMorphs('subscriber');`

How to resolve this?

**Comment by Omranic** [comment]
@yefta-me @abanghendri have you exported/published migrations?

If yes, then maybe you're running an outdated migrations because this field `subscriber` has been changed in a previous release. You'll need to remove your exported/published migrations and run the default ones, or republish again first.
