### ISSUE TITLE
Laravel doesn't read migrations and configs from published files

### ISSUE THREAD

**Issue by faramarzQ** [rinvex/laravel-subscriptions#177]
I installed laravel-subscriptions:v4.1.0 on Laravel:v7,
Now after publishing config and migration files, Laravel still reads them from the vendor diretory. any further actions should be done?

**Comment by Omranic** [comment]
The currently supported versions are Laravel v8+ and PHP v8.1+

So you'll need to use an older version compatible with Laravel v7, and check the PHP version compatibility too.

To use the published migrations instead of the package's ones, please disable the auto-migration config option https://github.com/rinvex/laravel-subscriptions/blob/master/config/config.php#L8
