### ISSUE TITLE
Use with different model

### ISSUE THREAD

**Issue by liran-co** [rinvex/laravel-subscriptions#63]
Can we use this on a different model (other than User)? We need subscriptions to be on an Account level (each account has multiple Users, so we can't store subscriptions on Users).

**Comment by Paulsky** [comment]
I had exactly the same question. After playing around with this package for a couple of minutes, I think this should work out of the box.

@liran-co I think you can use this with a different model other than User. The package uses a polymorphic relation, so it should work (on you Account model). Just use the HasSubscriptions trait on the Account model.

So I guess $planSubscription->user will return the Account model in this example. A bit awkward. I would suggest a rename of 'User' in this package to something like 'Subscriber'. 

@Omranic please confirm and could you please consider renaming the polymorphic User relation to 'Subscriber' or something like that instead of 'User' to make things more clear? Thanks for this great package by the way.

**Comment by bpuig** [comment]
I confirm @Paulsky comment, mine is configured like that, you can use another model giving it the HasSubscriptions trait.

+1 on the renaming, maybe it should be dynamic and take the name from the polymorphic relation. Many of us will have it not related to an user but to a customer, account, team, etc...

**Comment by Omranic** [comment]
Thank you for your patience, I confirm @Paulsky 's response.

In fact this discussion make sense, and I've renamed that relationship to `subscriber` instead of `user`.

Please note this is a breaking Change, if you have this package already installed, you'll need to rename one db field manually (check the changes in plan_subscriptions_table migration)
