### ISSUE TITLE
Cachable issue

### ISSUE THREAD

**Issue by izshreyansh** [rinvex/laravel-subscriptions#72]
Hi,
Do you think Cachable should be detached from the core rather than being implicit?
Or we can create an easy switch using config.

Consider this scenario
- Application User selects the subscription plan & makes payment. 
- We have created a new entry in `plan_subscriptions` 
- Now we want to let user access private pages because he is now a subscriber of our service.

But when we might go to check if the user is actually subscribed to the plan or not we might get the earlier cached result & user might still appear to be unsubscribed.

Your thoughts please?

**Comment by SvenSchoene** [comment]
I'm currently doing the following to disable the caching:

```php
<?php

namespace App\Models\Subscriptions;

use Illuminate\Database\Eloquent\Builder;
use Rinvex\Subscriptions\Models\PlanSubscription as RinvexPlanSubscription;

class PlanSubscription extends RinvexPlanSubscription
{

    public static function bootCacheableEloquent(): void
    {
    }

    public function newEloquentBuilder($query)
    {
        return new Builder($query);
    }
}
```

I'd rather have the option to explicitly enable a caching solution with my subscription feature.  
I love this library, though, so oh well. I'm fine implementing a workaround for now. Especially since I don't know what solution to suggest here. It seems to me that the way caching is implemented as a trait of the model, it's pretty much hard baked in. Maybe a variable that we can set `$enableCaching = false;`, which then is being used in the two methods I've overwritten above?

**Comment by Omranic** [comment]
Thank you so much for this useful discussion.

We've been discussing this recently, and since we got couple complains on baking caching in the core packages, I believe it's right to drop it from the core for more flexibility, and leave it up to the application layer, which is what we actually did in a recent commit https://github.com/rinvex/laravel-subscriptions/commit/830d0c5af6218c95bbcfb937bf6cfd751f3e4be6

Happy coding! 🙂
